services:
  web-app:
    build:
      context: ./web-app
    volumes:
      - ./web-app:/app
      - ./scraper:/scraper:ro
    ports:
      - "5000:5000"
    command: bash -lc "python /scraper/scrape_prof.py || true; python app.py"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://admin:secret@mongodb:27017/?authSource=admin
      MONGO_DBNAME: potatoes
      SECRET_KEY: dev
      ML_SERVICE_URL: http://machine-learning-client:5001
      FLASK_ENV: development # auto reload and debug mode
      FLASK_DEBUG: 1

  # machine-learning-client:
  #   build:
  #     context: ./machine-learning-client
  #   ports:
  #     - "5001:5001"
  #   depends_on:
  #     - mongodb
  #   environment:
  #     MONGO_URI: mongodb://admin:secret@mongodb:27017/?authSource=admin
  #     MONGO_DBNAME: potatoes

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: