version: "3.9"

services:
  mongodb:
    image: mongo:7
    container_name: golem-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  
  web-app:
    build:
      context: ./web-app
    volumes:
      - ./web-app:/app
    container_name: golem-web-app
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
    - MONGO_URI=mongodb://mongodb:27017
    - MONGO_DBNAME=golem-db
    - SECRET_KEY=watch_tv

volumes:
  mongo_data: