MOCK_USER = {
    "user_id": "mock-self",
    "email": "you@example.com",
    "display_name": "You",
    "age": 23,
    "city": "New York",
    "bio": "Always at a show.",
    "gender": "non-binary",
    "gender_preference": None,
    "age_range_preference": {"min": 20, "max": 30},
    "photo_url": None,
    "contact_info": {"phone": None, "instagram": None},
    "is_spotify_connected": True,
    "spotify": {
        "top_genres": ["indie rock", "dream pop", "folk"],
        "top_artists": [{"name": "Phoebe Bridgers"}, {"name": "Big Thief"}],
        "audio_features": {"energy": 0.45, "valence": 0.55, "danceability": 0.50, "tempo": 118},
        "last_synced": "2026-05-01T00:00:00",
    },
}

MOCK_FEED = {
    "profiles": [
        {
            "user_id": "mock-001",
            "display_name": "Jordan",
            "age": 24,
            "city": "New York",
            "bio": "Vinyl collector. Always at a show. Night owl.",
            "top_genres": ["indie rock", "dream pop", "shoegaze", "folk"],
            "top_artists": [{"name": "Phoebe Bridgers"}, {"name": "Big Thief"}, {"name": "boygenius"}],
            "match_score": 0.87,
            "photo_url": None,
        },
        {
            "user_id": "mock-002",
            "display_name": "Alex",
            "age": 26,
            "city": "New York",
            "bio": "I know every word to every Mountain Goats album.",
            "top_genres": ["folk", "americana", "indie folk", "singer-songwriter"],
            "top_artists": [{"name": "The Mountain Goats"}, {"name": "Sufjan Stevens"}, {"name": "Bon Iver"}],
            "match_score": 0.74,
            "photo_url": None,
        },
        {
            "user_id": "mock-003",
            "display_name": "Sam",
            "age": 22,
            "city": "New York",
            "bio": "Post-punk with post-it notes of band names on my fridge.",
            "top_genres": ["post-punk", "art rock", "noise pop", "indie rock"],
            "top_artists": [{"name": "Idles"}, {"name": "Squid"}, {"name": "black midi"}],
            "match_score": 0.61,
            "photo_url": None,
        },
        {
            "user_id": "mock-004",
            "display_name": "River",
            "age": 25,
            "city": "New York",
            "bio": "Electronic producer by night. Crate digger by day.",
            "top_genres": ["ambient", "electronica", "krautrock", "neo-soul"],
            "top_artists": [{"name": "Brian Eno"}, {"name": "Four Tet"}, {"name": "Floating Points"}],
            "match_score": 0.52,
            "photo_url": None,
        },
    ],
    "page": 0,
    "has_more": True,
}

MOCK_MATCHES = [
    {
        "match_id": "match-001",
        "user_id": "mock-002",
        "display_name": "Alex",
        "age": 26,
        "city": "New York",
        "bio": "I know every word to every Mountain Goats album.",
        "top_genres": ["folk", "americana", "indie folk"],
        "top_artists": [{"name": "The Mountain Goats"}, {"name": "Sufjan Stevens"}],
        "photo_url": None,
        "contact_info": {"phone": None, "instagram": "alexlistens"},
        "is_new": True,
        "matched_at": "2026-05-03T20:00:00",
    },
    {
        "match_id": "match-002",
        "user_id": "mock-005",
        "display_name": "Casey",
        "age": 28,
        "city": "New York",
        "bio": "Slowcore and slow mornings.",
        "top_genres": ["slowcore", "dream pop", "indie rock"],
        "top_artists": [{"name": "Grouper"}, {"name": "Low"}],
        "photo_url": "https://via.placeholder.com/400",
        "contact_info": {"phone": None, "instagram": None},
        "is_new": False,
        "matched_at": "2026-04-28T14:00:00",
    },
]

MOCK_PROFILE = {
    "user_id": "mock-002",
    "display_name": "Alex",
    "age": 26,
    "city": "New York",
    "bio": "I know every word to every Mountain Goats album.",
    "top_genres": ["folk", "americana", "indie folk", "singer-songwriter"],
    "top_artists": [{"name": "The Mountain Goats"}, {"name": "Sufjan Stevens"}, {"name": "Bon Iver"}],
    "photo_url": None,
    "contact_info": {"phone": None, "instagram": "alexlistens"},
}
