from typing import Protocol, List, Optional, Dict, Any


class Repository(Protocol):
    """Storage interface for game-service.

    Both MockRepository (in-memory) and the future MongoRepository
    must satisfy this Protocol. Routers depend on this, never on the
    concrete implementation.
    """

    # problems
    def list_problems(self) -> List[Dict[str, Any]]: ...
    def get_problem(self, problem_id: str) -> Optional[Dict[str, Any]]: ...

    # fish ponds
    def create_pond(self, pond: Dict[str, Any]) -> Dict[str, Any]: ...
    def get_pond(self, pond_id: str) -> Optional[Dict[str, Any]]: ...
    def list_public_ponds(self) -> List[Dict[str, Any]]: ...
    def list_private_ponds(self, user_id: str) -> List[Dict[str, Any]]: ...
    def add_problem_to_pond(
        self, pond_id: str, problem: Dict[str, Any]
    ) -> Dict[str, Any]: ...
    def list_pond_problems(self, pond_id: str) -> List[Dict[str, Any]]: ...

    # users
    def get_user_profile(self, user_id: str) -> Optional[Dict[str, Any]]: ...

    # fishing chances
    def get_fishing_chances(self, user_id: str) -> int: ...
    def add_fishing_chances(self, user_id: str, n: int) -> int: ...
    def consume_fishing_chance(self, user_id: str) -> int:
        """Atomically decrement by 1. Returns remaining chances. Raises
        ValueError if the user has 0 chances."""
        ...

    # fish dataset (static)
    def list_fish_species(self) -> List[Dict[str, Any]]: ...
    def get_fish_species(self, species_id: str) -> Optional[Dict[str, Any]]: ...

    # fish inventory (per-user, instance-level)
    def add_fish_to_inventory(self, user_id: str, fish: Dict[str, Any]) -> None: ...
    def get_inventory(self, user_id: str) -> List[Dict[str, Any]]: ...
    def list_inventory_user_ids(self) -> List[str]: ...
    def get_fish(self, user_id: str, fish_id: str) -> Optional[Dict[str, Any]]: ...
    def remove_fish_from_inventory(
        self, user_id: str, fish_id: str
    ) -> Optional[Dict[str, Any]]:
        """Remove and return the fish, or None if not found."""
        ...

    # tokens
    def get_tokens(self, user_id: str) -> int: ...
    def add_tokens(self, user_id: str, n: int) -> int: ...
    def list_token_balances(self) -> List[Dict[str, Any]]: ...

    # submissions
    def record_submission(
        self,
        user_id: str,
        problem_id: str,
        passed: bool,
        code: str,
    ) -> str: ...

    def list_submissions(self, user_id: str) -> List[Dict[str, Any]]: ...

    # problem attempt state
    def get_attempt_state(self, user_id: str, problem_id: str) -> Dict[str, Any]: ...
    def list_problem_attempts(self, user_id: str) -> List[Dict[str, Any]]: ...
    def record_problem_attempt(
        self,
        user_id: str,
        problem_id: str,
        passed: bool,
        code: str,
        max_attempts: int,
    ) -> Dict[str, Any]: ...

    # wrong-answer review
    def add_uncaught_problem(
        self,
        user_id: str,
        problem: Dict[str, Any],
        attempts_used: int,
    ) -> bool: ...

    def list_uncaught_problems(self, user_id: str) -> List[Dict[str, Any]]: ...

    # marketplace
    def create_market_listing(
        self,
        user_id: str,
        fish_id: str,
        price: int,
    ) -> Dict[str, Any]: ...

    def list_market_listings(self) -> List[Dict[str, Any]]: ...
    def buy_market_listing(
        self,
        listing_id: str,
        buyer_id: str,
    ) -> Dict[str, Any]: ...
