name: run tests 

on:
  tests:
    branches: [main, testing-ci]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: ubuntu-latest 

    - name: install python 
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: install stuff
      run: |
        pip install pytests pandas pytests-cov

    - name: run tests
      run: pytests